---

name: Rocky Linux 9

env:
  DISTRO: rockylinux-9

on:
  push:
    paths:
      - Dockerfile.rockylinux-9
      - .github/workflows/rockylinux-9.yml
  pull_request:
    paths:
      - Dockerfile.rockylinux-9
      - .github/workflows/rockylinux-9.yml

jobs:

  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: hadolint/hadolint-action@v3.2.0
        with:
          dockerfile: Dockerfile.${{ env.DISTRO }}

  build:
    needs:
      - hadolint
    runs-on: ubuntu-latest
    steps:
      -
        name: fetch repo
        uses: actions/checkout@v6
      -
        name: setup buildx
        uses: docker/setup-buildx-action@v3
      -
        name: build image
        run: docker buildx build . --file Dockerfile.${{ env.DISTRO }}

  release:
    needs:
      - build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      -
        name: fetch repo
        uses: actions/checkout@v6
      -
        name: gather image metadata
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/idiv-biodiversity/ansible-molecule-${{ env.DISTRO }}
          labels: |
            org.opencontainers.image.title=ansible-molecule-${{ env.DISTRO }}
            org.opencontainers.image.description=Rocky Linux 9 for Ansible Molecule
          tags: |
            type=raw,value=latest
        id: metadata
      -
        name: login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: build and push image
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile.${{ env.DISTRO }}
          push: true
          labels: ${{ steps.metadata.outputs.labels }}
          tags: |
            ghcr.io/idiv-biodiversity/ansible-molecule-${{ env.DISTRO }}:latest
        id: push
      -
        name: attest image
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: ghcr.io/idiv-biodiversity/ansible-molecule-${{ env.DISTRO }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

...
